{
 "title": "API Refit",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Self Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck{healthcheck=\"self\", job=\"API_Refit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Elastic Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck{healthcheck=\"elasticsearch\", job=\"API_Refit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(http_requests_received_total{job=\"API_Refit\"}[1m])",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(increase(http_requests_received_total{job=\"API_Refit\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "id": "1",
       "settings": {},
       "type": "logs"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}