extensions:
  health_check:
    endpoint: 127.0.0.1:13133

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector-metrics
          scrape_interval: 10s
          static_configs:
            - targets: ["127.0.0.1:8754"]
        - job_name: grafana-metrics
          scrape_interval: 10s
          static_configs:
            - targets: ["grafana:3000"]
  tcplog:
    listen_address: 0.0.0.0:54526
    operators:
      - type: regex_parser
        regex: (?P<timestamp_field>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z)
      - type: add
        field: body
        value: EXPR(replace(body, attributes.timestamp_field, 'Oct 11 22:14:15'))
      - type: syslog_parser
        protocol: rfc3164
        location: UTC
      - type: time_parser
        parse_from: attributes.timestamp_field
        layout: "%Y-%m-%dT%H:%M:%SZ"
        layout_type: strptime
      - type: move
        if: "attributes.message != nil"
        from: attributes.message
        to: body
      - type: remove
        field: attributes.timestamp_field
      - type: remove
        field: attributes.proc_id
      - type: remove
        field: attributes.priority
      - type: remove
        field: attributes.facility

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 10
  batch:
    send_batch_size: 8192
    timeout: 1s
    send_batch_max_size: 0
  resource:
    attributes:
      - action: insert
        key: service.name
        value: grafana

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true
  otlphttp/prometheus:
    endpoint: http://prometheus:9090/api/v1/otlp
    encoding: proto
    tls:
      insecure: true
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true
  debug:
    verbosity: detailed
    sampling_initial: 2
    sampling_thereafter: 200

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/prometheus] # prometheusremotewrite
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [tcplog]
      processors: [memory_limiter, resource, batch]
      exporters: [otlphttp/loki]
  extensions: [health_check]
  telemetry:
    resource:
      service.name: grafana-opentelemetry/metrics
      author: monitoriginartist
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: 127.0.0.1
                port: 8754
                with_resource_constant_labels:
                  included:
                    - service.name
                    - author
    logs:
      level: debug
      encoding: json
