{
 "title": "API EntityFramework",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Self Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck{healthcheck=\"self\", job=\"API_EntityFramework\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sql Server (AppDataContext) Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck{healthcheck=\"AppDataContext\", job=\"API_EntityFramework\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso CPU % ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_runtime_cpu_usage{job=\"API_EntityFramework\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória Utilizada",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_working_set_bytes{job=\"API_EntityFramework\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_count{job=\"API_EntityFramework\"}[1m])",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=\"API_EntityFramework\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Taxa Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{job=\"API_EntityFramework\"}[1m])",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"API_EntityFramework\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Análise de Latência HTTP por Percentil",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{job=\"API_EntityFramework\"}[1m])) by (le))",
     "legendFormat": "Percentil 50 (0.5) - Latência"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket{job=\"API_EntityFramework\"}[1m])) by (le))",
     "legendFormat": "Percentil 90 (0.9) - Latência"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"API_EntityFramework\"}[1m])) by (le))\r\n",
     "legendFormat": "Percentil 95 (0.95) - Latência"
    }
   ]
  }
 ]
}