services:
  otel:
    image: grafana/otel-lgtm:0.7.1
    ports:
      - "3000:3000"
      - "4317:4317"
      - "9090:9090"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true