USE [master]
GO

/****** Object:  Database [PerformRetriveData]    Script Date: 10/10/2024 10:18:40 ******/
CREATE DATABASE [PerformRetriveData]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PerformRetriveData', FILENAME = N'/var/opt/mssql/data/PerformRetriveData.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PerformRetriveData_log', FILENAME = N'/var/opt/mssql/data/PerformRetriveData_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PerformRetriveData].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PerformRetriveData] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PerformRetriveData] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PerformRetriveData] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PerformRetriveData] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PerformRetriveData] SET ARITHABORT OFF 
GO

ALTER DATABASE [PerformRetriveData] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PerformRetriveData] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PerformRetriveData] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PerformRetriveData] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PerformRetriveData] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PerformRetriveData] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PerformRetriveData] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PerformRetriveData] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PerformRetriveData] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PerformRetriveData] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PerformRetriveData] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PerformRetriveData] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PerformRetriveData] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PerformRetriveData] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PerformRetriveData] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PerformRetriveData] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PerformRetriveData] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PerformRetriveData] SET RECOVERY FULL 
GO

ALTER DATABASE [PerformRetriveData] SET  MULTI_USER 
GO

ALTER DATABASE [PerformRetriveData] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PerformRetriveData] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PerformRetriveData] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PerformRetriveData] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PerformRetriveData] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PerformRetriveData] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PerformRetriveData] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PerformRetriveData] SET  READ_WRITE 
GO


