{
 "title": "API ErrorHandler",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Healths", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Self Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck{healthcheck=\"self\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Elastic Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "healthcheck{healthcheck=\"elasticsearch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API ErrorHandler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_requests_received_total[1m])",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(increase(http_requests_received_total[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "id": "1",
       "settings": {},
       "type": "logs"
      }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}