global:
  # Acao que define o tempo que o prometheus vai solicitar a informacao do servidor, vai fazer um pull no servidor de 15 em 15 segs pra coletar as metricas
  scrape_interval: 15s 
  evaluation_interval: 15s

scrape_configs:
  
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'API_ErrorHandler'
    metrics_path: /metrics
    scrape_timeout: 10s
    tls_config:
      insecure_skip_verify: true 
    scheme: https
    static_configs:
      - targets: ['host.docker.internal:7173']

  - job_name: 'API_Refit'
    metrics_path: /metrics
    scrape_timeout: 10s
    tls_config:
      insecure_skip_verify: true 
    scheme: https
    static_configs:
      - targets: ['host.docker.internal:7223']

  - job_name: 'API_EntityFramework'
    metrics_path: /metrics
    scrape_timeout: 10s
    tls_config:
      insecure_skip_verify: true 
    scheme: https
    static_configs:
      - targets: ['host.docker.internal:7197']